version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/tcSlackBuildNotifier

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:

      - checkout

      - restore_cache:
          key: tcSlackBuildNotifier-{{ checksum "pom.xml" }}

#      - run: mvn install:install-file -Dfile=target/tcslackbuildnotifier-core-1.4.18.jar -DgroupId=petegoo.teamcity.plugins.tcslacknotifications -DartifactId=tcslackbuildnotifier -Dversion=1.4.18 -Dpackaging=jar

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: tcSlackBuildNotifier-{{ checksum "pom.xml" }}

      - run: mvn clean

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/tcslackbuildnotifier-*.zip